### ISSUE TITLE
Explore adding Tunable QF via Coefficients 

### ISSUE THREAD

**Issue by ufkhan97** [gitcoinco/qf-calculator#7]
Explore if we could partner with TEC to:
- Be able to add an area where users could upload coefficients that override PMBD coefficients 

@Jmiller4

**Comment by ufkhan97** [comment]
This could merge with filter in/filter out

**Comment by Jmiller4** [comment]
Implemented in https://github.com/gitcoinco/qf-calculator/commit/405cabccf11c9c44456229588143145881398b8c
